monolog:
    channels:
        - deprecation
        - security
        - off_api

    handlers:
        main:
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%.log"
            level:    debug
            channels: ["!event"]

        console:
            type:     console
            channels: ["!event", "!doctrine", "!console"]

        security:
            type:     stream
            path:     "%kernel.logs_dir%/security.log"
            level:    info
            channels: [security]

        off_api:
            type:     stream
            path:     "%kernel.logs_dir%/off_api.log"
            level:    info
            channels: [off_api]

        deprecation:
            type:     stream
            path:     "%kernel.logs_dir%/deprecation.log"
            channels: [deprecation]
