# Route pour afficher le formulaire 2FA
2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
    path: /2fa_check
    defaults:
        _controller: scheb_two_factor.form_controller::checkAction
