parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/*/Entity/'
            - '../src/Domain/*/Event/'
            - '../src/Domain/*/Repository/'
            - '../src/Kernel.php'

    App\Infrastructure\Persistence\DoctrineUserRepository:
        arguments:
            $registry: '@doctrine'

    App\Infrastructure\Persistence\DoctrineDashboardRepository:
        arguments:
            $registry: '@doctrine'

    App\Domain\User\Repository\UserRepositoryInterface:
        alias: App\Infrastructure\Persistence\DoctrineUserRepository
        public: true

    App\Domain\Dashboard\Repository\DashboardRepositoryInterface:
        alias: App\Infrastructure\Persistence\DoctrineDashboardRepository
        public: true

    App\Application\Port\OpenFoodFactsClientInterface:
        alias: App\Infrastructure\Http\OpenFoodFactsClient
        public: true
